# Generated by Django 5.2.5 on 2025-08-22 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_name_alter_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdori')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sabab')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='products.product')),
            ],
        ),
    ]
