# Generated by Django 5.2.5 on 2025-08-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_ready_alter_profile_added_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
