# Generated by Django 5.2.5 on 2025-08-24 15:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_description_alter_profile_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='added_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='Not set', max_length=150),
        ),
    ]
