# Generated by Django 5.2.5 on 2025-08-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_receipt_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
