# Generated by Django 5.2.5 on 2025-08-16 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_name_alter_product_price_and_more'),
        ('sale', '0003_receipt_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptitem',
            name='price',
        ),
        migrations.AddField(
            model_name='receiptitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
    ]
