# Generated by Django 5.2.5 on 2025-08-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_remove_receiptitem_price_receiptitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptitem',
            name='product',
        ),
        migrations.AddField(
            model_name='receiptitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
