# Generated by Django 5.2.5 on 2025-08-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_name_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qrcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='QR Kod'),
        ),
    ]
