# Generated by Django 5.2.7 on 2025-11-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_location_profile_name'),
        ('products', '0006_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qrcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='QR Kod'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Miqdori'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('profile', 'qrcode')},
        ),
    ]
